name: Wake Render Server

on:
  # 7:30 AM - 8:00 AM IST
  schedule:
    - cron: "0,5,10,15,20,25,30 2 * * *"

  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Chroma Server
        run: |
          echo "Waking server..."

          curl -L \
            --max-time 120 \
            --retry 5 \
            --retry-delay 15 \
            --user-agent "Mozilla/5.0" \
            https://ai-interview-chroma.onrender.com/api/v1/heartbeat

          echo "Done"